<a href="https://colab.research.google.com/github/aaradhyasirohi/MachineLearning/blob/main/ML_dummy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
from google.colab import files
files.upload()

Saving homeprices.csv to homeprices.csv

{'homeprices.csv': b'town,area,price\nmonroe township,2600,550000\nmonroe township,3000,565000\nmonroe township,3200,610000\nmonroe township,3600,680000\nmonroe township,4000,725000\nwest windsor,2600,585000\nwest windsor,2800,615000\nwest windsor,3300,650000\nwest windsor,3600,710000\nrobinsville,2600,575000\nrobinsville,2900,600000\nrobinsville,3100,620000\nrobinsville,3600,695000\n'}

In [5]:
df=pd.read_csv("homeprices.csv")
dummies=pd.get_dummies(df["town"])

In [8]:
merged=pd.concat([df,dummies],axis="columns")
merged

               town  area   price  monroe township  robinsville  west windsor
0   monroe township  2600  550000             True        False         False
1   monroe township  3000  565000             True        False         False
2   monroe township  3200  610000             True        False         False
3   monroe township  3600  680000             True        False         False
4   monroe township  4000  725000             True        False         False
5      west windsor  2600  585000            False        False          True
6      west windsor  2800  615000            False        False          True
7      west windsor  3300  650000            False        False          True
8      west windsor  3600  710000            False        False          True
9       robinsville  2600  575000            False         True         False
10      robinsville  2900  600000            False         True         False
11      robinsville  3100  620000            False         True         False
12      robinsville  3600  695000            False         True         False

In [12]:
final=merged.drop(['town','west windsor'],axis='columns')
#final

In [13]:
from sklearn.linear_model import LinearRegression

In [18]:
model=LinearRegression()
x=final.drop('price',axis='columns')
y=final.price
model.fit(x,y)

LinearRegression()

In [23]:
model.predict([[7000,1,0]])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([1098058.4820468])

In [24]:
model.score(x,y)

0.9573929037221872

In [25]:
df

               town  area   price
0   monroe township  2600  550000
1   monroe township  3000  565000
2   monroe township  3200  610000
3   monroe township  3600  680000
4   monroe township  4000  725000
5      west windsor  2600  585000
6      west windsor  2800  615000
7      west windsor  3300  650000
8      west windsor  3600  710000
9       robinsville  2600  575000
10      robinsville  2900  600000
11      robinsville  3100  620000
12      robinsville  3600  695000

In [27]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfle=df
dfle.town=le.fit_transform(df['town'])
dfle

    town  area   price
0      0  2600  550000
1      0  3000  565000
2      0  3200  610000
3      0  3600  680000
4      0  4000  725000
5      2  2600  585000
6      2  2800  615000
7      2  3300  650000
8      2  3600  710000
9      1  2600  575000
10     1  2900  600000
11     1  3100  620000
12     1  3600  695000

In [47]:
x=dfle[['town','area']].values
y=dfle['price']
x

array([[   0, 2600],
       [   0, 3000],
       [   0, 3200],
       [   0, 3600],
       [   0, 4000],
       [   2, 2600],
       [   2, 2800],
       [   2, 3300],
       [   2, 3600],
       [   1, 2600],
       [   1, 2900],
       [   1, 3100],
       [   1, 3600]])

In [49]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(drop='first', sparse_output=False), [0])  # ONLY town
    ],
    remainder='passthrough'
)

x = ct.fit_transform(x)
x

array([[0.0e+00, 0.0e+00, 2.6e+03],
       [0.0e+00, 0.0e+00, 3.0e+03],
       [0.0e+00, 0.0e+00, 3.2e+03],
       [0.0e+00, 0.0e+00, 3.6e+03],
       [0.0e+00, 0.0e+00, 4.0e+03],
       [0.0e+00, 1.0e+00, 2.6e+03],
       [0.0e+00, 1.0e+00, 2.8e+03],
       [0.0e+00, 1.0e+00, 3.3e+03],
       [0.0e+00, 1.0e+00, 3.6e+03],
       [1.0e+00, 0.0e+00, 2.6e+03],
       [1.0e+00, 0.0e+00, 2.9e+03],
       [1.0e+00, 0.0e+00, 3.1e+03],
       [1.0e+00, 0.0e+00, 3.6e+03]])

In [52]:
model.fit(x,y)
model.predict([[1,0,30000]])

array([4042386.04601149])

In [53]:
model.score(x,y)

0.9573929037221873

In [ ]:
##########       lect 7